import React from 'react';
import Head from 'next/head';
import { Container, Navbar, Nav } from 'react-bootstrap';
import styles from './Header.module.css';
import Image from 'next/image';
import { FaHome } from 'react-icons/fa';
import { FiUser } from 'react-icons/fi';


export const Header = () => {

  return (
    <>
        <Head>
            <title>cv counselor</title>
            <meta name="description" content="Generated by create next app" />
            <meta httpEquiv="X-UA-Compatible" content="IE=7" />
            <meta httpEquiv="Content-Type" content="text/html;charset=UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <header className={styles.header_sticky}>
            <Navbar collapseOnSelect expand="lg" variant="dark">
            <Container>
                <Navbar.Brand href="#home">
                    <Image src="/images/logo.png" width="120px" height="60px" alt="Logo"></Image>
                </Navbar.Brand>
                <Navbar.Toggle aria-controls="responsive-navbar-nav" />
                <Navbar.Collapse className="position-relative" id="responsive-navbar-nav">
                    <Nav className={`${styles.menu_list} m-auto px-3`}>
                        <Nav.Link className='-mt-1 d-none d-sm-block'> <FaHome /> </Nav.Link>
                        <Nav.Link href="#features">Find Counselors</Nav.Link>
                        <Nav.Link href="#pricing">Video Consult</Nav.Link>
                        <Nav.Link href="#pricing">Courses</Nav.Link>
                        <Nav.Link href="#pricing">Testimonials</Nav.Link>
                    </Nav>
                    <Nav className={styles.login_main}>
                        <Nav.Link href="#deets" className='text-white'> <span><FiUser /> <span className={styles.loginText}>Login/Signup</span> </span> </Nav.Link>
                    </Nav>
                </Navbar.Collapse>
                </Container>
            </Navbar>
        </header>
    </>
  )
}

export default Header;